version: "3.8"

services:
  flask-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container's port 5000 to host's port 5000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
